version: '3.4'

services:

  sub-microservice:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   ports:
      - "3000:80"

  sub-microservice-dapr:
    command: ["./daprd",
      "-app-id", "pubsub",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/config/config.yaml"        
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./config/:/config"